
import argparse
import os

import numpy as np
import torch
import torch.nn as nn
from torchvision import datasets

import train_model as tm


def parse_args():
    parser = argparse.ArgumentParser(
        description="Evaluate CorrosionAI using the saved train/validation/test split."
    )
    parser.add_argument(
        "--data-root",
        default="data/dataset",
        help="Dataset root in ImageFolder format.",
    )
    parser.add_argument(
        "--split",
        default="outputs/model_development/split_indices.npz",
        help="Path to split_indices.npz generated by develop/train_model.py.",
    )
    parser.add_argument(
        "--weights",
        default="outputs/model_development/best_acc.pth",
        help="Path to best_acc.pth generated by train_model.py.",
    )
    parser.add_argument(
        "--output",
        default="outputs/model_development/test_results",
        help="Output folder for metrics, reports, and confusion matrices.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed used for deterministic DataLoader behavior.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=32,
        help="Batch size used during evaluation.",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=4,
        help="Number of DataLoader workers.",
    )
    parser.add_argument(
        "--device",
        default="auto",
        choices=["auto", "cpu", "cuda"],
        help="Evaluation device.",
    )
    parser.add_argument(
        "--split-name",
        default="test",
        choices=["train", "val", "test", "all"],
        help="Which split to evaluate.",
    )
    return parser.parse_args()


def configure_train_module(args):
    tm.DATA_ROOT = args.data_root
    tm.OUT_DIR = args.output
    tm.SEED = args.seed
    tm.BATCH_SIZE = args.batch_size
    tm.NUM_WORKERS = args.num_workers

    if args.device == "auto":
        tm.DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    elif args.device == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested, but no CUDA device is available.")
        tm.DEVICE = torch.device("cuda:0")
    else:
        tm.DEVICE = torch.device("cpu")


def load_checkpoint(model, checkpoint_path):
    checkpoint = torch.load(checkpoint_path, map_location=tm.DEVICE)
    if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
        model.load_state_dict(checkpoint["model_state_dict"])
    else:
        model.load_state_dict(checkpoint)
    model.to(tm.DEVICE)
    model.eval()
    return model


def main():
    args = parse_args()
    configure_train_module(args)
    os.makedirs(args.output, exist_ok=True)

    if not os.path.exists(args.split):
        raise FileNotFoundError(
            f"Split file not found: {args.split}\n"
            "Run develop/train_model.py first, or pass the correct --split path."
        )
    if not os.path.exists(args.weights):
        raise FileNotFoundError(f"Checkpoint not found: {args.weights}")

    split_data = np.load(args.split)
    train_idx = split_data["train_idx"]
    val_idx = split_data["val_idx"]
    test_idx = split_data["test_idx"]

    dataset = datasets.ImageFolder(root=args.data_root, transform=None)
    classes = dataset.classes
    num_classes = len(classes)

    print("Using device:", tm.DEVICE)
    print("Dataset:", args.data_root)
    print("Classes:", classes)
    print(f"Split sizes: train/val/test = {len(train_idx)}/{len(val_idx)}/{len(test_idx)}")
    print("Checkpoint:", args.weights)

    tm.set_seed(args.seed)
    train_loader, train_eval_loader, val_loader, test_loader = tm.build_loaders(
        args.data_root,
        train_idx,
        val_idx,
        test_idx,
        args.seed,
    )

    model = tm.build_model(num_classes)
    model = load_checkpoint(model, args.weights)
    criterion = nn.CrossEntropyLoss()

    loaders = {
        "train": train_eval_loader,
        "val": val_loader,
        "test": test_loader,
    }

    split_names = ["train", "val", "test"] if args.split_name == "all" else [args.split_name]
    summary_rows = []

    for split_name in split_names:
        loss_value, metrics = tm.evaluate(model, loaders[split_name], criterion, classes)
        tm.save_split_outputs(split_name, loss_value, metrics, classes, args.output)

        summary_rows.append({
            "split": split_name,
            "loss": loss_value,
            "accuracy": metrics["acc"],
            "precision_macro": metrics["precision_macro"],
            "recall_macro": metrics["recall_macro"],
            "f1_macro": metrics["f1_macro"],
        })

        print(
            f"{split_name.upper()} | loss={loss_value:.6f} | "
            f"acc={metrics['acc']:.6f} | "
            f"macro-F1={metrics['f1_macro']:.6f}"
        )

    tm.save_dicts_to_csv(os.path.join(args.output, "evaluation_summary.csv"), summary_rows)
    print("Done. Results saved to:", args.output)


if __name__ == "__main__":
    main()
